version: '2'
services:
  ubuntu:
    container_name: ubuntu
    build:
      context: ./ubuntu
    dns: 8.8.8.8
    restart: always
  apache:
    container_name: apache
    build:
      context: ./apache
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    depends_on:
      - mysql
      - memcached
      - redis
      - elastic17
    volumes:
      - ./storage-for-images/apache-configs:/etc/apache2/sites-enabled
    dns: 8.8.8.8
  mysql:
    container_name: mysql
    build:
      context: ./mysql
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ~/Work/docker/storage-for-images/mysql:/var/lib/mysql
    dns: 8.8.8.8
  memcached:
    container_name: memcached
    build:
      context: ./memcached
    dns: 8.8.8.8
    ports:
      - "127.0.0.1:11211:11211"
  redis:
    container_name: redis
    build:
      context: ./redis
    volumes:
      - ~/Work/docker/storage-for-images/redis:/data
    dns: 8.8.8.8
    ports:
      - "127.0.0.1:6379:6379"
  elastic17:
    container_name: elastic17
    build:
      context: ./elastic17
    ports:
      - "127.0.0.1:9200:9200"
    volumes:
      - ~/Work/docker/storage-for-images/elasticsearch:/usr/share/elasticsearch/data
    dns: 8.8.8.8
  postgres:
    container_name: postgres
    build:
      context: ./postgres
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - DEBUG=false
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=
      - DB_TEMPLATE=
      - DB_EXTENSION=
    volumes:
      - /home/remigijus/Work/docker/storage-for-images/postgres:/var/lib/postgresql
